### ISSUE TITLE
[FEATURE REQUEST] Permission workaround

### ISSUE THREAD

**Issue by H4K0N42** [SapuSeven/BetterUntis#425] opened 2023-11-02 00:56 UTC
### Problem Statement

My school has blocked access to the free room and teacher section and I want to acess it

### Solution Ideas

Since I have acess to all normal timetables just check every timetable avalible for the room / teacher to get the info without the permission

**Comment by lm41** [comment] 2023-11-02 01:58
Duplicate of #381

**Closed as not planned** 2023-11-02 01:58 UTC
Labels: enhancement
