### ISSUE TITLE
Events that take place before lesson 1 do not show up

### ISSUE THREAD

**Issue by ou-li** [SapuSeven/BetterUntis#278] opened 2022-05-09 14:34 UTC
Supervising students in the hall...

![grafik](https://user-images.githubusercontent.com/7612981/167432725-cf78664c-6ab3-49ad-90c0-87d5fc39c32c.png)

![grafik](https://user-images.githubusercontent.com/7612981/167433210-dd1954ac-47b6-4433-aec1-1d34b4d25879.png)

Keep up the good work!

Regards

**Comment by lm41** [comment] 2022-05-09 15:02
BetterUntis has the `Timetable Range` setting. Can you try to experiment with this setting? I don't know if this helps, but i would at least try it.

**Comment by SapuSeven** [comment] 2023-02-15 02:15
Closing this as a duplicate of #153. Progress will be tracked there.

**Closed as completed by SapuSeven** 2023-02-15 02:15 UTC
Labels: enhancement
