### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by McToel** [SapuSeven/BetterUntis#170] opened 2021-01-13 22:00 UTC
**Description**

If I scroll down in day view, the app crashes as soon as I reach the end.

<details>
</details>

<details>
  <summary><b>Logs</b></summary>

  I cannot find a stack trace that I can copy paste
</details>

**Additional information**

 - Android version: 10 (lineade_star2lte)
 - BetterUntis version: 3.4.4 (28)
 - Installation source: F-Droid

**Comment by SapuSeven** [comment] 2021-01-13 22:08
Please provide details of your issue as described in the template text.

**Comment by McToel** [comment] 2021-01-18 14:18
Sorry I was on the go, so I did not have a look at the created Bug report. I thought it would autofill the fields. But I have edited it now.

**Comment by SapuSeven** [comment] 2021-01-18 14:53
Seems to be a duplicate of #165

**Closed as completed** 2021-03-22 23:14 UTC
Labels: bug, duplicate
