### ISSUE TITLE
[Bug Report] ? Showing instead of classes

### ISSUE THREAD

**Issue by Greyhash-dev** [SapuSeven/BetterUntis#417] opened 2023-09-21 06:05 UTC
### Steps to Reproduce

Open the app and select a timetable

### Expected Result

No "?"

### Actual Result

Instead of classes "?" and instead of some hours "?"
![Screenshot_20230921-080438_BetterUntis](https://github.com/SapuSeven/BetterUntis/assets/65809634/a3cf7d2b-fa2f-4b4b-9006-d7e4ff5ad968)
![Screenshot_20230921-080432_BetterUntis](https://github.com/SapuSeven/BetterUntis/assets/65809634/8c47383f-e296-42ab-ac01-c25d23db8949)
![Screenshot_20230921-080310_BetterUntis~2](https://github.com/SapuSeven/BetterUntis/assets/65809634/0b155b9b-68ca-4682-963a-857a6a787599)

### Android Version

Android 12L

### BetterUntis Version

4.0.2

### Installation Source

F-Droid

### Additional information

2 years ago everything was working totally fine, last year teachers were not showing up anymore and this year I have the stated issues (maybe API changes?)

**Comment by SapuSeven** [comment] 2023-09-21 08:04
Duplicate of #416: Please re-login (see https://github.com/SapuSeven/BetterUntis/issues/416#issuecomment-1723192724)

**Closed as completed** 2023-09-21 08:04 UTC
Labels: bug
