### ISSUE TITLE
Teacher names not shown

### ISSUE THREAD

**Issue by EmilEmilchen** [SapuSeven/BetterUntis#352] opened 2023-02-08 18:34 UTC
It might just be my stupidity but the App doesnt show any teacher names. The original "Untis Mobile" app does however show all the names just fine. Ill attach 2 screenshots. From the original app and BetterUntis (the "van Gee" is the teachers name). Its all in german...![Screenshot_20230208-193407_Untis Mobile.png](https://user-images.githubusercontent.com/70268797/217620879-383c35e2-04b8-4668-b9ba-d39df00bc4fc.png)

![Screenshot_20230208-193159_BetterUntis.png](https://user-images.githubusercontent.com/70268797/217620895-cfe0da89-9d11-46f1-b6a2-47c9633771ca.png)

**Comment by lm41** [comment] 2023-02-14 23:22
possible duplicate of #158

**Comment by SapuSeven** [comment] 2023-02-15 02:06
@lm41 I think so too.
@EmilEmilchen can you please look at #158 and see if you can do the steps I posted in my last comment?

**Closed as not planned** 2023-02-15 02:06 UTC
Labels: bug, duplicate
