### ISSUE TITLE
[Bug Report] Libraries are not loading 

### ISSUE THREAD

**Issue by Lauritz-Tieste** [SapuSeven/BetterUntis#401] opened 2023-07-28 17:24 UTC
### Steps to Reproduce

Open the libraries section 

### Expected Result

The libraries should load

### Actual Result

No libraries displayed 

### Android Version

Android 13 / OneUI 5.1

### BetterUntis Version

Version 4.0.1 (28131459)

### Installation Source

Google Play

**Comment by Lauritz-Tieste** [comment] 2023-07-28 17:27
I had internet 😄

**Comment by Lauritz-Tieste** [comment] 2023-09-02 22:21
still happening in 4.0.2 (28227720)

**Comment by lm41** [comment] 2023-09-08 19:21
Thats odd. I'm investigating this right now

**Comment by lm41** [comment] 2023-09-08 20:00
This is caused by this line: https://github.com/SapuSeven/BetterUntis/blob/3aee9078bc4a59ec8c637e287f91f06a87805a80/gradle.properties#L17-L17

Is there a reason why you added this in c2d8de52 @SapuSeven?

**Comment by SapuSeven** [comment] 2023-09-09 07:04
I tried to reduce build times:
https://medium.com/@sagar.das/reduce-android-app-build-times-by-enabling-gradle-configuration-cache-927b46476712

**Comment by lm41** [comment] 2023-09-11 03:20
There is a bug report at the libraries github for this:
https://github.com/mikepenz/AboutLibraries/issues/857

The folks from davx5 just disabled the configuration cache for release builds:
https://github.com/bitfireAT/davx5-ose/pull/339#issuecomment-1586120468

**Comment by Lauritz-Tieste** [comment] 2023-11-04 17:17
How could the error be fixed?

**Comment by SapuSeven** [comment] 2023-11-07 03:01
Fixed in 6f924eb11a0bb80ee6042f5fb94c31d05180466b

**Closed as completed by SapuSeven** 2023-11-07 03:01 UTC
Labels: bug
