### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by johahauf** [SapuSeven/BetterUntis#296] opened 2022-09-10 09:11 UTC
<details>
<summary>Logs</summary>

```
Anfragen-ID: 5
Fehlercode: 3
Fehlermeldung: u7.h: Unexpected JSON token at offset 8728: Expected start of the array '[', but had ':' instead
JSON input: ....."excuseStatuses":[],"holidays":null,"klassen":[{"id":997,"na.....
```
</details>

**Additional information**

- Android version: _10_
- BetterUntis version: _3.5.0 (33)_
- Installation source: _com.android.vending_

**Comment by lm41** [comment] 2022-09-10 09:54
Duplicate of #294

**Closed as completed** 2022-09-10 10:31 UTC
