### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by philsrfn** [SapuSeven/BetterUntis#261] opened 2022-02-04 07:04 UTC
<details>
<summary>Logs</summary>

```
Anfragen-ID: 3
Fehlercode: 3
Fehlermeldung: o7.b: Field 'staffInfo' is required for type with serial name 'com.sapuseven.untis.models.untis.timetable.PeriodText', but it was missing
```
</details>

**Additional information**

- Android version: _11_
- BetterUntis version: _3.4.7 (31)_
- Installation source: _org.fdroid.fdroid_

**Comment by lm41** [comment] 2022-02-04 14:14
Duplicate of https://github.com/SapuSeven/BetterUntis/issues/245 https://github.com/SapuSeven/BetterUntis/issues/246 https://github.com/SapuSeven/BetterUntis/issues/247 https://github.com/SapuSeven/BetterUntis/issues/250 https://github.com/SapuSeven/BetterUntis/issues/251 https://github.com/SapuSeven/BetterUntis/issues/252 https://github.com/SapuSeven/BetterUntis/issues/254 https://github.com/SapuSeven/BetterUntis/issues/255 https://github.com/SapuSeven/BetterUntis/issues/257 https://github.com/SapuSeven/BetterUntis/issues/258 https://github.com/SapuSeven/BetterUntis/issues/259 #260 . This has been fixed in version 3.4.8. You can opt-in as a beta tester on Google Play to receive the update sooner

**Closed as completed** 2022-02-04 16:13 UTC
Labels: bug
