### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by steinm** [SapuSeven/BetterUntis#257] opened 2022-02-01 06:02 UTC
<details>
<summary>Logs</summary>

```
Anfragen-ID: 10
Fehlercode: 3
Fehlermeldung: o7.b: Field 'staffInfo' is required for type with serial name 'com.sapuseven.untis.models.untis.timetable.PeriodText', but it was missing
```
</details>

**Additional information**

- Android version: _9_
- BetterUntis version: _3.4.7 (31)_
- Installation source: _com.google.android.packageinstaller_

**Comment by lm41** [comment] 2022-02-01 06:17
Duplicate of #245 #246 #247 #250 #251 #252 #254 #255. This has been fixed in version 3.4.8. You can opt-in as a beta tester on Google Play to receive the update sooner.

**Closed as completed** 2022-02-01 09:01 UTC
Labels: bug
