### ISSUE TITLE
[Bug Report] Day is displayed three times

### ISSUE THREAD

**Issue by Domi04151309** [SapuSeven/BetterUntis#42] opened 2020-01-25 10:52 UTC
**Description**

The same day is displayed three times when swiping through the days.

<details>
  <summary><b>Video</b></summary>

  [BetterUntis Bug Report 25012020](https://youtu.be/-0vm_rJV-bA) 
</details>

<details>
  <summary><b>Logs</b></summary>

  No crash occured
</details>

**Additional information**

 - Android version: Android 10
 - BetterUntis version: 3.2.1(17)
 - Installation source: Google Play

**Comment by SapuSeven** [comment] 2020-01-25 11:00
Duplicate of #39 and already fixed.
Available in the next release, or use the debug build from my website (see [#39](https://github.com/SapuSeven/BetterUntis/issues/39#issuecomment-577690981)).

**Closed as completed** 2020-01-25 11:00 UTC
Labels: bug
