### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by ChrisPHL** [SapuSeven/BetterUntis#310] opened 2022-09-20 04:56 UTC
<details>
<summary>Logs</summary>

```
Anfragen-ID: 5
Fehlercode: 3
Fehlermeldung: o7.b: Field 'staffInfo' is required for type with serial name 'com.sapuseven.untis.models.untis.timetable.PeriodText', but it was missing
```
</details>

**Additional information**

- Android version: _10_
- BetterUntis version: _3.4.7 (31)_
- Installation source: _com.aurora.store_

**Comment by SapuSeven** [comment] 2022-09-25 20:45
Duplicate of #245 - This has already been fixed.
Please update the app to fix the problem.

**Closed as completed by SapuSeven** 2022-09-25 20:45 UTC
Labels: bug, duplicate
