### ISSUE TITLE
[Feature Request] A feature with which you can give individual subjects a color

### ISSUE THREAD

**Issue by Sensi1707** [SapuSeven/BetterUntis#420] opened 2023-10-17 15:11 UTC
### Problem Statement

All school subjects look the same in the app and it's kind of monotonous. It would be great if you could change the color of individual subjects

**Comment by schmaller** [comment] 2023-10-29 22:47
@Sensi1707 , this seems to me to be a duplicate of #329 .
If not, could you explain the difference, please.

**Closed as not planned** 2023-11-04 14:22 UTC
Labels: duplicate, enhancement
