### ISSUE TITLE
[Feature Request] Bookmark / favorites for classes / teachers and rooms

### ISSUE THREAD

**Issue by svesa11** [SapuSeven/BetterUntis#133] opened 2020-10-03 09:17 UTC
ist would bei great to Bookmark / favotite classes, teachers and rooms for example in the sidebar or as an Icon on the top-line.
Thank you for the great work!!!

**Comment by Domi04151309** [comment] 2020-10-03 10:10
Duplicate of #66

**Comment by SapuSeven** [comment] 2020-10-07 16:51
Thanks, this is a great idea.

As mentioned, I'm closing this issue as duplicate of #66.

**Closed as completed by SapuSeven** 2020-10-07 16:51 UTC
Labels: duplicate, enhancement
