### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by W113565456** [SapuSeven/BetterUntis#326] opened 2022-11-23 18:57 UTC
<details>
<summary>Logs</summary>

```
Anfragen-ID: 1
Fehlercode: -7001
Fehlermeldung: invalid element type: 12
```
</details>

**Additional information**

- Android version: _10_
- BetterUntis version: _3.5.1 (34)_
- Installation source: _com.android.vending_

**Comment by SapuSeven** [comment] 2022-11-24 23:31
Duplicate of #325

**Closed as completed by SapuSeven** 2022-11-24 23:31 UTC
