### ISSUE TITLE
[Feature Request]  Speed Dial List for classes

### ISSUE THREAD

**Issue by gitpower2017** [SapuSeven/BetterUntis#118] opened 2020-09-18 05:04 UTC
A speed dial list for the different classes would be very useful for students.
We have more than one child

**Comment by Domi04151309** [comment] 2020-09-18 05:05
What do you mean by speed dial list?

**Comment by SapuSeven** [comment] 2020-09-18 05:12
I believe this is a duplicate of #66.

**Comment by gitpower2017** [comment] 2020-09-18 06:46
A shortcut for the classes.
I have more than one school child using Untis.
Our school has only one student LOGIN for all classes

**Comment by Domi04151309** [comment] 2020-09-18 07:43
The widgets PR will add class shortcuts that can be placed on the home screen. Furthermore, a favorites feature is planned.

**Comment by SapuSeven** [comment] 2022-05-02 10:26
This feature is finally available in version 3.5.0.

**Closed as completed by SapuSeven** 2022-05-02 10:26 UTC
Labels: duplicate, enhancement
