### ISSUE TITLE
[Bug Report] Login works, but timetable shows "bad credentials" error

### ISSUE THREAD

**Issue by DerBraky** [SapuSeven/BetterUntis#112] opened 2020-09-13 20:39 UTC
<details>
<summary>Crash Log</summary>

```
Request ID: 0
Error code: -8504
Error message: bad credentials
```
</details>

**Comment by SapuSeven** [comment] 2020-09-13 20:55
This does not look like an actual bug of BetterUntis.
Maybe your password or the Untis Mobile access key changed
Please try logging in again (open the drawer, tap on your current profile to open the drop down list, then long-press on your profile in this list. This takes you to the login screen where you can correct your credentials as needed.)

**Comment by DC7IA** [comment] 2020-09-18 06:06
I think I've got the same problem.

Login intially works, but then it says that the credentials are wrong when I try to refresh.

To get the newest version I have to remove my account and re-add it all the time.

dc7ia

**Comment by SapuSeven** [comment] 2020-09-18 09:01
Are you using the Untis Mobile API Key or your password to log in?

**Comment by DC7IA** [comment] 2020-09-22 09:03
I'm using the password.

**Comment by SapuSeven** [comment] 2022-11-27 02:16
Closing this as I can't reproduce the issue.
Feel free to re-open if the issue still exists in the current version.

**Closed as not planned by SapuSeven** 2022-11-27 02:16 UTC
Labels: bug
