### ISSUE TITLE
[Crash Report] widget crashed

### ISSUE THREAD

**Issue by p6thos** [SapuSeven/BetterUntis#277] opened 2022-05-02 05:32 UTC
![Screenshot_20220502-072621_Pixel Launcher](https://user-images.githubusercontent.com/77694883/166188622-aae31e96-1699-4cff-8517-0556e5545bbb.png)
#
[logs-1651469231416.zip](https://github.com/SapuSeven/BetterUntis/files/8600958/logs-1651469231416.zip)
<details>
<summary>Logs</summary>

```
Bitte füge die komprimierten Log-Dateien als Anhang hinzu.
Diese wurden hier gespeichert: `/storage/emulated/0/Android/data/com.sapuseven.untis/files/logs-1651469231416.zip`
```
</details>

**Additional information**

- Android version: _12_
- BetterUntis version: _3.4.8 (32)_
- Installation source: _com.android.vending_

**Comment by SapuSeven** [comment] 2022-05-02 08:23
Duplicate of #238 .
Will be addressed in the next release.

**Closed as completed by SapuSeven** 2022-05-02 08:23 UTC
