### ISSUE TITLE
"Failed to load timetable" even if notifications disabled

### ISSUE THREAD

**Issue by Perflyst** [SapuSeven/BetterUntis#23] opened 2019-11-17 14:47 UTC
If the timetable cannot load in the morning because there is no internet connection I get a notification "Failed to load Timetable - You wont get any notification today" even if the notifications are disabled in the settings.

**Comment by SapuSeven** [comment] 2019-11-20 16:58
Are you sure you disabled the preference? I cannot reproduce this issue and also didn't find any error in the program logic...

**Comment by Perflyst** [comment] 2019-11-20 17:00
Yes it was disabled.
I did a clean install of BetaUntis and disabled again, will report back in the next few days

**Comment by SapuSeven** [comment] 2019-11-20 17:02
Another thought: Did you create more than one profile at any point?

**Comment by SapuSeven** [comment] 2019-11-28 23:21
Should be fixed it in the referenced commits.

**Closed as completed** 2019-11-28 23:21 UTC
Labels: bug
